name: Swift

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:
  unit-tests-cocoapods:
    name: Unit tests (CocoaPods)
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update CocoaPods repo
        run: |
          pod repo update
      
      - name: Install CocoaPods
        run: |
          pod install
          
      - name: Run tests
        run: xcodebuild -workspace 'LifeSum.xcworkspace' -scheme 'LifeSum' -destination 'platform=iOS Simulator,name=iPhone 12' test
      - name: Build App
        run: xcodebuild -workspace 'LifeSum.xcworkspace' -scheme 'LifeSum' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO

